---
name: stimulus-form
services:
  app:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
    volumes:
      - "../..:/workspaces:cached"
    command: sleep infinity
    networks:
      - default
    ports:
      - 45678:45678
      - 3036:3036
      - 3037:3037