ARG RUBY_VERSION

FROM ruby:$RUBY_VERSION-slim-bullseye

ARG NODE_VERSION
ARG YARN_VERSION

RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  build-essential \
  gnupg2 \
  curl \
  less \
  nano \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

RUN curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  nodejs \
  yarn=$YARN_VERSION-1 \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3

RUN gem update --system

RUN mkdir -p /app

WORKDIR /app

# FROM node:$NODE_VERSION-bullseye-slim

# ARG YARN_VERSION

# # Dependências do sistema
# RUN apt-get update -qq \
#   && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
#   build-essential \
#   gnupg2 \
#   curl \
#   less \
#   nano \
#   && apt-get clean \
#   && rm -rf /var/cache/apt/archives/* \
#   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
#   && truncate -s 0 /var/log/*log

# RUN corepack enable && corepack prepare yarn@1.22.19 --activate

# RUN mkdir -p /app

# WORKDIR /app
