ARG NODE_VERSION

FROM node:$NODE_VERSION-bullseye-slim

ARG YARN_VERSION

# Dependências do sistema
RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  build-essential \
  gnupg2 \
  curl \
  less \
  nano \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

RUN corepack enable && corepack prepare yarn@1.22.19 --activate

RUN mkdir -p /app

WORKDIR /app
